export const projectsData = [
  {
    title: "RDAPP",
    bullets: [
      "I Contributed to building and maintaining core modules such as Tickets Management, Roles & Permissions, Dashboards, and Reporting systems.",
      "One of the key features I worked on was a dynamic Question Builder, allowing users to create customizable forms with flexible answer structures and generate detailed reports.",
      "Integrated RESTful APIs and AWS S3 for structured data flow and efficient media handling",
      "Managed complex business logic and form state to ensure scalable and dynamic user flows",
      "Contributed to code reviews and task distribution within a cross-functional team",
    ],
    techStack: [
      "React.js",
      "Redux",
      "API Integration",
      "Bootstrap",
      "Formik",
      "Axios",
      "AWS S3",
    ],
    image: "assets/images/projects/rdapp.png",
    link: "https://rdapp-tfi-cpv-ca2x.onrender.com/login",
    ariaLabel: "RDAPP",
  },
  {
    title: "EndUser – Client",
    subTitle: "(Integrated with RDAPP)",
    bullets: [
      "Designed and implemented a scalable multi-module system (Projects, Tickets) with role-based access control",
      "Integrated real-time updates using Socket.IO and managed secure file storage with AWS S3",
      "Managed server state efficiently using React Query and handled global state with Zustand",
      "Built a fully responsive, multilingual UI with robust form validation using Zod and React Hook Form",
    ],
    techStack: [
      "React.js",
      "Zustand",
      "Tailwind CSS",
      "Socket.IO",
      "i18next",
      "AWS S3",
      "API Integration",
      "firebase",
      "Axios",
    ],
    image: "assets/images/projects/end-user.png",
    link: "https://end-user-new-yids.onrender.com/login",
    ariaLabel: "EndUser",
  },
  {
    title: "ElMullim – E-Learning Platform",
    bullets: [
      "Implemented seamless course browsing, lesson streaming, and complex user management workflows",
      "Utilized React Query for efficient caching and Redux for global state, ensuring high performance",
      "Integrated i18n for full multi-language support and handled complex validations using Zod",
      "Focused on clean architecture and reusable UI components for maximum scalability",
    ],
    techStack: [
      "React.js",
      "TypeScript",
      "React Query",
      "Redux",
      "i18next",
      "Zod",
      "Tailwind CSS",
      "Framer Motion",
      "Axios",
    ],
    image: "assets/images/projects/elmullim.png",
    link: "https://elmullim-frontend.vercel.app/home",
    ariaLabel: "ElMullim",
  },
  {
    title: "Fresh Cart E-Commerce",
    bullets: [
      "Integrated RESTful APIs for products, authentication (JWT), and order management",
      "Built persistent cart functionality with real-time updates to enhance user experience",
      "Structured efficient state and API handling for high UI responsiveness",
      "Developed responsive and interactive UI using Tailwind CSS and Swiper.js",
    ],
    techStack: [
      "React.js",
      "React Query",
      "Tailwind CSS",
      "Axios",
      "JWT Auth",
      "Swiper.js",
    ],
    image: "assets/images/projects/fresh-cart.png",
    link: "https://e-commerce-fresh-cart-plum.vercel.app/",
    ariaLabel: "Fresh Cart",
  },
  {
    title: "Professional Law Firm",
    bullets: [
      "Built a fully responsive multi-page website optimized across all devices",
      "Implemented smooth scrolling and interactive UI elements to improve engagement",
      "Created reusable components for services, team sections, and contact forms",
      "Ensured cross-browser compatibility and adherence to accessibility standards",
    ],
    techStack: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "JavaScript",
      "Responsive Design",
    ],
    image: "assets/images/projects/legal.png",
    link: "https://legal-frim-template.vercel.app/",
    ariaLabel: "Legal Firm",
  },
  {
    title: "Restaurant & Food Delivery",
    bullets: [
      "Designed an engaging menu interface with categorized navigation and visual hierarchy",
      "Developed interactive UI elements including animations and hover effects",
      "Implemented a fully responsive grid system for seamless multi-device experience",
      "Optimized images and performance for faster load times",
    ],
    techStack: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "Bootstrap",
      "Responsive Design",
    ],
    image: "assets/images/projects/bistro-bliss.png",
    link: "https://food-website-cyan-five.vercel.app/",
    ariaLabel: "Restaurant & Food",
  },
  {
    title: "Movies Explorer",
    bullets: [
      "Implemented real-time search with debouncing for optimized API requests",
      "Integrated Appwrite for backend services including data storage and user management",
      "Built a responsive, Netflix-inspired UI using Tailwind CSS and Shadcn",
      "Enhanced performance through efficient API handling and fast content rendering",
    ],
    techStack: [
      "React.js",
      "Tailwind CSS",
      "Shadcn",
      "Appwrite",
      "TMDB",
      "Axios",
    ],
    image: "assets/images/projects/movies.png",
    link: "https://movies-website-v2.vercel.app/",
    ariaLabel: "Movies Explorer",
  },
];
