export const projectsData = [
  {
    title: "RDAPP",
    subtitle: "Enterprise Admin Dashboard",
    description:
      "Enterprise-grade admin platform powering daily operations at DomApp",
    bullets: [
      "Architected scalable frontend with modular component design across 10+ feature modules",
      "Engineered core modules for Tickets, Roles/Permissions, and a Dynamic Question Builder for automated reporting",
      "Integrated RESTful APIs and AWS S3 for structured data flow and efficient media handling",
      "Managed complex business logic and form state to ensure scalable and dynamic user flows",
      "Contributed to code reviews and task distribution within a cross-functional team",
    ],
    techStack: [
      "React.js",
      "Redux",
      "RESTful APIs",
      "Bootstrap",
      "Formik",
      "Axios",
      "AWS S3",
    ],
    image: "assets/images/projects/rdapp.png",
    link: "https://rdapp-tfi-cpv-ca2x.onrender.com/login",
    ariaLabel: "View RDAPP",
  },
  {
    title: "EndUser – Client Dashboard",
    subtitle: "Integrated Project Management System",
    description:
      "Multi-module client portal integrated with RDAPP for project lifecycle management",
    bullets: [
      "Developed a multi-module architecture (Projects, Tickets, Reports) with role-based access control",
      "Integrated Socket.IO for live updates and AWS S3 for secure project assets management",
      "Leveraged React Query for server state and Zustand for global state management",
      "Optimized responsive UI with i18n multi-language support and Zod/React Hook Form validations",
    ],
    techStack: [
      "React.js",
      "TanStack Query",
      "Zustand",
      "Tailwind CSS",
      "Socket.IO",
      "i18next",
      "AWS S3",
    ],
    image: "assets/images/projects/end-user.png",
    link: "https://end-user-new-yids.onrender.com/login",
    ariaLabel: "View EndUser System",
  },
  {
    title: "ElMullim – E-Learning Platform",
    subtitle: "LMS Platform",
    description:
      "Full-featured learning management system with role-based access for students, parents, and instructors",
    bullets: [
      "Implemented seamless course browsing, lesson streaming, and complex user management workflows",
      "Utilized React Query for efficient caching and Redux for global state, ensuring high performance",
      "Integrated i18n for full multi-language support and handled complex validations using Zod",
      "Focused on clean architecture and reusable UI components for maximum scalability",
    ],
    techStack: [
      "React.js",
      "TypeScript",
      "React Query",
      "Redux",
      "i18next",
      "Zod",
      "Bootstrap",
    ],
    image: "assets/images/projects/elmullim.png",
    link: "https://elmullim-frontend.vercel.app/home",
    ariaLabel: "View ElMullim",
  },
  {
    title: "Fresh Cart E-Commerce",
    subtitle: "Online Shopping Application",
    description:
      "Modern e-commerce platform with dynamic product catalog and seamless checkout flow",
    bullets: [
      "Integrated REST APIs for dynamic product data, user authentication (JWT), and order processing",
      "Built persistent cart management with real-time updates and optimized shopping experience",
      "Architected efficient state management and API handling to ensure UI responsiveness",
      "Developed responsive UI components using Tailwind CSS and Swiper.js for product displays",
    ],
    techStack: [
      "React.js",
      "React Query",
      "Tailwind CSS",
      "Axios",
      "JWT Auth",
      "Swiper.js",
    ],
    image: "assets/images/projects/fresh-cart.png",
    link: "https://e-commerce-fresh-cart-plum.vercel.app/",
    ariaLabel: "View Fresh Cart",
  },
  {
    title: "Professional Law Firm",
    subtitle: "Corporate Website",
    description:
      "Polished corporate website built for a legal services firm focusing on trust and responsiveness.",
    bullets: [
      "Developed a fully responsive multi-page layout optimized for all device viewports",
      "Implemented smooth scroll animations and interactive sections to enhance user engagement.",
      "Built reusable component structure for services, team profiles, and contact forms",
      "Ensured cross-browser compatibility and accessibility compliance across all pages.",
    ],
    techStack: [
      "HTML5",
      "CSS3",
      "Bootstrap",
      "JavaScript",
      "Responsive Design",
    ],
    image: "assets/images/projects/legal.png",
    link: "https://legal-frim-template.vercel.app/",
    ariaLabel: "View Legal Firm Website",
  },
  {
    title: "Restaurant & Food Delivery",
    subtitle: "UI/UX Frontend",
    description:
      "Visually rich food ordering interface designed to maximize engagement and conversion",
    bullets: [
      "Crafted a visually appealing menu showcase with high-quality image grids and category-based navigation",
      "Built interactive UI components including animated food cards, hover effects, and smooth transitions",
      "Implemented responsive grid layout adapting seamlessly across all screen sizes",
      "Optimized image loading and page performance for faster initial render times",
    ],
    techStack: [
      "HTML5",
      "CSS3",
      "JavaScript",
      "Bootstrap",
      "Responsive Design",
    ],
    image: "assets/images/projects/bistro-bliss.png",
    link: "https://food-website-cyan-five.vercel.app/",
    ariaLabel: "View Restaurant & Food UI Project",
  },
  {
    title: "Movies Explorer",
    subtitle: "Movie Discovery Platform",
    description:
      "Dynamic discovery platform integrated with TMDB API for up-to-date cinema data",
    bullets: [
      "Built real-time search with debounced API calls and instant result rendering",
      "Integrated Appwrite as a backend solution for data persistence and user collections",
      "Engineered a fully responsive layout with Netflix-inspired UI using Tailwind CSS and Shadcn",
      "Focused on fast content rendering and efficient API handling for seamless browsing",
    ],
    techStack: [
      "React.js",
      "Tailwind CSS",
      "Shadcn",
      "Appwrite",
      "TMDB",
      "Axios",
    ],
    image: "assets/images/projects/movies.png",
    link: "https://movies-website-v2.vercel.app/",
    ariaLabel: "View Movies Explorer",
  },
];
